### ISSUE TITLE
作者您好，请问这个公式如何推导的呢？突然出现的转置矩阵不太清楚。

### ISSUE THREAD

**Issue by WangzcBruce** [MengyuWang826/SegRefiner#1]
![image](https://github.com/MengyuWang826/SegRefiner/assets/45158420/a8de831f-a944-4f0a-a592-a3793f6ca127)
![image](https://github.com/MengyuWang826/SegRefiner/assets/45158420/8ec1f49e-ffa7-423a-a21f-4781fd55dd69)
用贝叶斯推导公式的话，如上图所示，没有出现转置矩阵欸

**Comment by MengyuWang826** [comment]
> ![image](https://private-user-images.githubusercontent.com/45158420/292973443-a8de831f-a944-4f0a-a592-a3793f6ca127.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzMxNzQsIm5iZiI6MTcwMzY3Mjg3NCwicGF0aCI6Ii80NTE1ODQyMC8yOTI5NzM0NDMtYThkZTgzMWYtYTk0NC00ZjBhLWE1OTItYTM3OTNmNmNhMTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEwMjc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4Y2M2Mzc5NjAzZTA0NmM5YWE5NGVhN2U5NWRlYTk0OThhYWMwMTg5NjMwOWU0OWY0N2M3MGZjNjMxOGYwZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qvJ96SOFnQwZDSViHoRfffp9BrZA6INl1mwg_BZ9YEQ) ![image](https://private-user-images.githubusercontent.com/45158420/292973578-8ec1f49e-ffa7-423a-a21f-4781fd55dd69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzMxNzQsIm5iZiI6MTcwMzY3Mjg3NCwicGF0aCI6Ii80NTE1ODQyMC8yOTI5NzM1NzgtOGVjMWY0OWUtZmZhNy00MjNhLWEyMWYtNDc4MWZkNTVkZDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEwMjc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NmE1OWY0ODVjNzE1OWI5ZGQ3NTVlOWQ0MTU2YmFlNTgxYTgyYTNhMTUwZDIyMjliYmEzYWE5NzgwODJjNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aPNBRvqt6QyMXhVy6XikjeJPHoXrtZVmFNMmdLeRs6s) 用贝叶斯推导公式的话，如上图所示，没有出现转置矩阵欸

你图中展示的第8步的结果是带有x_{t-1}的，而p(x_{t-1}|x_t)显然不应该依赖于这一项，所以出现了形式的不同。式(9)的详细推导过程可以在Appendix.A中找到。
The result shown in the 8 step of your diagram includes x_{t-1}, while p(x_{t-1}|x_t) should obviously not depend on this term, leading to a discrepancy in the form. A detailed derivation of Equ.(9) can be found in Appendix A.
