### ISSUE TITLE
关于训练和推理阶段Transition Sample Module的输入

### ISSUE THREAD

**Issue by wzx0720** [MengyuWang826/SegRefiner#2]
作者您好，感谢您的出色工作！
在您的论文中，训练阶段Transition Sample Module将前一个mask mt-1、粗糙mask mT分别与当前t的状态转移概率相乘来计算mt，但您在附录中的算法中使用的是这个公式：
![image](https://github.com/MengyuWang826/SegRefiner/assets/130528393/f0d652c1-380e-4192-8154-a67172aa8d43)
另外，在推理阶段论文中您的表述是：
![image](https://github.com/MengyuWang826/SegRefiner/assets/130528393/b2214859-cf35-45b0-9e6c-4f2ababfeb61)
其中使用的是mt-1，但附录中的算法使用的是粗糙mask：
![image](https://github.com/MengyuWang826/SegRefiner/assets/130528393/dea64043-df79-474a-bb44-446a3fb5c226)

请问应该如何理解Transition Sample Module的输入呢？具体以哪个表述为准？感谢您的解答！

**Comment by MengyuWang826** [comment]
> 作者您好，感谢您的出色工作！ 在您的论文中，训练阶段Transition Sample Module将前一个mask mt-1、粗糙mask mT分别与当前t的状态转移概率相乘来计算mt，但您在附录中的算法中使用的是这个公式： ![image](https://private-user-images.githubusercontent.com/130528393/293633194-f0d652c1-380e-4192-8154-a67172aa8d43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTc4NTYsIm5iZiI6MTcwNDI1NzU1NiwicGF0aCI6Ii8xMzA1MjgzOTMvMjkzNjMzMTk0LWYwZDY1MmMxLTM4MGUtNDE5Mi04MTU0LWE2NzE3MmFhOGQ0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwNDUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjViZWE2NzEyZWY4MTE3MmU3ZjZlM2JmNjhjYzA0NzZlYWRjYTdiMDY3N2VjNjkxMjliZTdkN2IzODdhMDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RRIAcHGjupUwXtF-C8HDcx4MqQbRNDGVSqtgtder500) 另外，在推理阶段论文中您的表述是： ![image](https://private-user-images.githubusercontent.com/130528393/293633332-b2214859-cf35-45b0-9e6c-4f2ababfeb61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTc4NTYsIm5iZiI6MTcwNDI1NzU1NiwicGF0aCI6Ii8xMzA1MjgzOTMvMjkzNjMzMzMyLWIyMjE0ODU5LWNmMzUtNDViMC05ZTZjLTRmMmFiYWJmZWI2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwNDUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjdlNDU3NTlkMjI5YzQ1MzhlYWExODFjYTUyMDUxNDgzNjc2MDNjNjY5ZjVlY2IxNjdjYTJlNDczNmY5OWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lpr9LYnWOxm9n3J8RzuB9O0P_HLBZ1dK6NhjtAWB2Fk) 其中使用的是mt-1，但附录中的算法使用的是粗糙mask： ![image](https://private-user-images.githubusercontent.com/130528393/293633274-dea64043-df79-474a-bb44-446a3fb5c226.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTc4NTYsIm5iZiI6MTcwNDI1NzU1NiwicGF0aCI6Ii8xMzA1MjgzOTMvMjkzNjMzMjc0LWRlYTY0MDQzLWRmNzktNDc0YS1iYjQ0LTQ0NmEzZmI1YzIyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwNDUyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODIxODg2ZmU5ZjNhZWFmNmVjMGI3MDhjMmY4MWIzNGM3ODYwY2UwZGJkOGRlMGY2YjhmY2U4MTI3YzY2MzIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UuA0tRR5eOGg5Z7prLs4jfgcXh7CJOAp8XjOhgWcoJk)
> 
> 请问应该如何理解Transition Sample Module的输入呢？具体以哪个表述为准？感谢您的解答！

这个在原理的推导上，由于前向/反向过程都是单向的，所以在前向过程中使用 $m_{t-1}$ 或 $m_0$ ，在反向过程中使用 $m_t$ 或 $m_T$ ，是等效的（图中的 $M_{fine}$ 和 $M_{coarse}$ 就是 $m_0$ 和 $m_T$ ）。
而在实现中，由于训练过程我们希望直接得到中间某一步的 $m_t$ （而非迭代获得），所以输入是$M_{fine}$ ；而推理过程是迭代进行的，所以使用的是 $m_t$ 。
