### ISSUE TITLE
KeyError: 'coarsename'

### ISSUE THREAD

**Issue by liangxuejingjing** [MengyuWang826/SegRefiner#3]
Thank you for publishing this excellent work~
When I run the `python tools/train.py configs/segrefiner/segrefiner_hr.py` according to your readme， there is a problem here：
`Original Traceback (most recent call last):
  File "/opt/conda/envs/segrefiner/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/segrefiner/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/segrefiner/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mmdetection/SegRefiner-main/mmdet/datasets/hr_collection.py", line 77, in __getitem__
    data = self.pipeline(results)
  File "/mmdetection/SegRefiner-main/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/mmdetection/SegRefiner-main/mmdet/datasets/pipelines/loading.py", line 864, in __call__
    results = self.load_coarse_mask(results)
  File "/mmdetection/SegRefiner-main/mmdet/datasets/pipelines/loading.py", line 849, in load_coarse_mask
    filename = osp.join(results['img_prefix'], results['img_info']['coarsename'])
KeyError: 'coarsename'`

How can I get the “coarsename”？

**Comment by liangxuejingjing** [comment]
`python tools/test.py configs/segrefiner/segrefiner_dis.py checkpoints/segrefiner_hr_latest.pth --out_dir /mmdetection/SegRefiner-main/output/
/opt/conda/envs/segrefiner/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
load checkpoint from local path: checkpoints/segrefiner_hr_latest.pth
Traceback (most recent call last):
  File "tools/test.py", line 237, in <module>
    main()
  File "tools/test.py", line 205, in main
    model.CLASSES = dataset.CLASSES
AttributeError: 'DISDataset' object has no attribute 'CLASSES'`

**Comment by MengyuWang826** [comment]
> When I TEST using `python tools/test.py configs/segrefiner/segrefiner_dis.py checkpoints/segrefiner_hr_latest.pth --out_dir /mmdetection/SegRefiner-main/output/ /opt/conda/envs/segrefiner/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details. warnings.warn( load checkpoint from local path: checkpoints/segrefiner_hr_latest.pth Traceback (most recent call last): File "tools/test.py", line 237, in <module> main() File "tools/test.py", line 205, in main model.CLASSES = dataset.CLASSES AttributeError: 'DISDataset' object has no attribute 'CLASSES'`

Thank you for your feedback. I will test it out and fix this bug.

**Comment by MengyuWang826** [comment]
> Thank you for publishing this excellent work~ When I run the `python tools/train.py configs/segrefiner/segrefiner_hr.py` according to your readme， there is a problem here： `Original Traceback (most recent call last): File "/opt/conda/envs/segrefiner/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop data = fetcher.fetch(index) File "/opt/conda/envs/segrefiner/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/opt/conda/envs/segrefiner/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp> data = [self.dataset[idx] for idx in possibly_batched_index] File "/mmdetection/SegRefiner-main/mmdet/datasets/hr_collection.py", line 77, in __getitem__ data = self.pipeline(results) File "/mmdetection/SegRefiner-main/mmdet/datasets/pipelines/compose.py", line 41, in __call__ data = t(data) File "/mmdetection/SegRefiner-main/mmdet/datasets/pipelines/loading.py", line 864, in __call__ results = self.load_coarse_mask(results) File "/mmdetection/SegRefiner-main/mmdet/datasets/pipelines/loading.py", line 849, in load_coarse_mask filename = osp.join(results['img_prefix'], results['img_info']['coarsename']) KeyError: 'coarsename'`
> 
> How can I get the “coarsename”？

This issue was due to the missing information in the JSON file obtained by the script `scripts/gen_coarse_masks_hr.py`. It has now been fixed. If you have previously run the script and stored the coarse masks used for training, you can also obtain the correct JSON file by running `scripts/get_collect_json.py`.

**Comment by MengyuWang826** [comment]
> When I TEST using `python tools/test.py configs/segrefiner/segrefiner_dis.py checkpoints/segrefiner_hr_latest.pth --out_dir /mmdetection/SegRefiner-main/output/ /opt/conda/envs/segrefiner/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details. warnings.warn( load checkpoint from local path: checkpoints/segrefiner_hr_latest.pth Traceback (most recent call last): File "tools/test.py", line 237, in <module> main() File "tools/test.py", line 205, in main model.CLASSES = dataset.CLASSES AttributeError: 'DISDataset' object has no attribute 'CLASSES'`

This is also fixed. Thank you for your feedback!
