### ISSUE TITLE
Condition on original image

### ISSUE THREAD

**Issue by jkli1998** [MengyuWang826/SegRefiner#8]
Thank you very much for your excellent work!
I have a question, is this model denoised with the original image as a condition? I couldn't find the relevant code.

**Comment by MengyuWang826** [comment]
> Thank you very much for your excellent work! I have a question, is this model denoised with the original image as a condition? I couldn't find the relevant code.

Thank you for your attention to this work. The model indeed uses the original image as a condition in a concatenation manner to perform denoising. As an example, during the training process, this step is completed at line 79 in [segrefiner_base.py](https://github.com/MengyuWang826/SegRefiner/blob/main/mmdet/models/detectors/segrefiner_base.py)

**Comment by jkli1998** [comment]
> > Thank you very much for your excellent work! I have a question, is this model denoised with the original image as a condition? I couldn't find the relevant code.
> 
> Thank you for your attention to this work. The model indeed uses the original image as a condition in a concatenation manner to perform denoising. As an example, during the training process, this step is completed at line 79 in [segrefiner_base.py](https://github.com/MengyuWang826/SegRefiner/blob/main/mmdet/models/detectors/segrefiner_base.py)

Got it. Thanks for your kind reply :)
